### ISSUE TITLE
Does not register brood of bram globals

### ISSUE THREAD

**Issue by Gizmo7706** [euloggeradmin/LootNanny#14] opened 2023-01-12 07:06 UTC
Hi!

It seams like the regex for globals does not work with aurli cave globals, at least it missed 2 globals on brood of bram.

Line 222616: 2023-01-12 06:47:25 [Globals] [] Christer toad Johansson killed a creature (Disecter, Brood of Bram) with a value of 91 PED!
Line 224556: 2023-01-12 06:56:36 [Globals] [] Christer toad Johansson killed a creature (Disecter, Brood of Bram) with a value of 54 PED!

**Comment by anton-danielsson** [comment] 2023-02-05 14:50
The problem is the `,` in the name of the creature: "Disecter, Brood of Bram"
It needs to be added here: https://github.com/euloggeradmin/LootNanny/blob/main/chat.py#L135

**Comment by euloggeradmin** [comment] 2023-03-25 20:05
Will be fixed on v0.0.11

**Closed by euloggeradmin** 2023-03-25 20:05 UTC
